services:
  servidor_apache:
    container_name: asirJa_apache_web
    image: httpd:latest
    ports:
      - "80:80"
    # Mapeamos el directorio raíz (equipo:contenedor)  
    volumes:
      - ./Paginas:/usr/local/apache2/htdocs
      - ./conf:/usr/local/apache2/conf   
    networks:
      xoela_subnet:
        ipv4_address: 162.22.5.1

  servidor_dns:
    container_name: asir_Javiercitoserver_dns
    image: ubuntu/bind9
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #Mapeo de puertos
    networks:
      xoela_subnet:
        ipv4_address: 162.22.5.10
    volumes:
      - ./configuracion:/etc/bind
      - ./zonas:/var/lib/bind
      #Para mapear los directorios
  
  cliente:
    container_name: asirJa_cliente_web
    image: ubuntu
    platform: linux/amd64
    tty: true
    stdin_open: true
    dns:
      - 162.22.5.10

    networks:
      xoela_subnet:
        ipv4_address: 162.22.5.20

networks:
  xoela_subnet:
    external: true